### ISSUE TITLE
文档中添加支持的芯片列表

### ISSUE THREAD

**Issue by QiuToo** [OpenCloudOS/opencloudos.github.io#8]
如果可以在文档中添加OpencloudOS支持的CPU（比如英特尔、AMD、鲲鹏、海光等），这是个非常棒的想法。

**Comment by bartdong** [comment]
感谢，非常好的建议！

**Comment by bartdong** [comment]
https://docs.opencloudos.org/guide/adaptation/
已更新，欢迎查阅！
